"use client";

import { FormEvent, useEffect, useState } from "react";
import { ArrowRight, BriefcaseBusiness, CheckCircle2, Eye, EyeOff, Loader2, LockKeyhole, Mail, Sparkles } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

export function AuthScreen() {
  const [mode,setMode]=useState<"login"|"register">("login"); const[email,setEmail]=useState(""); const[password,setPassword]=useState(""); const[showPassword,setShowPassword]=useState(false); const[loading,setLoading]=useState(false); const[googleLoading,setGoogleLoading]=useState(false); const[message,setMessage]=useState<{type:"ok"|"error";text:string}|null>(null);
  useEffect(()=>{const error=new URLSearchParams(window.location.search).get("auth_error");if(error==="google_not_registered"){setMode("register");setMessage({type:"error",text:"Akun Google tersebut belum terdaftar. Silakan register menggunakan email dan password terlebih dahulu, lalu verifikasi emailmu."})}else if(error){setMessage({type:"error",text:"Link autentikasi tidak valid atau sudah kedaluwarsa."})}},[]);
  function client(){const supabase=createClient();if(!supabase)setMessage({type:"error",text:"Supabase belum dikonfigurasi. Isi URL dan anon key pada .env.local."});return supabase}
  async function submit(e:FormEvent){e.preventDefault();setLoading(true);setMessage(null);const supabase=client();if(!supabase){setLoading(false);return}if(mode==="register"){const{data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:`${window.location.origin}/auth/callback?next=/dashboard`}});if(error)setMessage({type:"error",text:error.message});else if(data.user?.identities?.length===0)setMessage({type:"error",text:"Email ini sudah terdaftar. Silakan kembali ke Login."});else setMessage({type:"ok",text:`Link verifikasi telah dikirim ke ${email}. Verifikasi email sebelum login.`})}else{const{error}=await supabase.auth.signInWithPassword({email,password});if(error){const unverified=error.message.toLowerCase().includes("confirm");setMessage({type:"error",text:unverified?"Email belum diverifikasi. Buka email verifikasi yang kami kirim.":"Email atau password tidak cocok. Jika belum memiliki akun, pilih Register."});if(!unverified)setMode("register")}else window.location.href="/dashboard"}setLoading(false)}
  async function loginGoogle(){setGoogleLoading(true);setMessage(null);const supabase=client();if(!supabase){setGoogleLoading(false);return}const{error}=await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:`${window.location.origin}/auth/callback?next=/dashboard`,queryParams:{prompt:"select_account"}}});if(error){setMessage({type:"error",text:error.message});setGoogleLoading(false)}}

  return <main className="grid min-h-screen bg-white lg:grid-cols-[1.08fr_.92fr]">
    <section className="relative hidden overflow-hidden bg-navy p-12 text-white lg:flex lg:flex-col lg:justify-between"><div className="absolute -right-24 -top-24 h-80 w-80 rounded-full bg-teal/15 blur-3xl"/><div className="absolute -bottom-32 left-1/4 h-96 w-96 rounded-full bg-blue-500/10 blur-3xl"/><a href="/" className="relative flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-teal text-lg font-bold">J</span><span className="text-2xl font-bold">JobTrackr</span></a><div className="relative max-w-xl"><span className="mb-6 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-4 py-2 text-xs font-semibold text-teal-100"><Sparkles size={14}/> One application a day</span><h1 className="text-5xl font-bold leading-[1.08] tracking-tight">Your next opportunity starts with today&apos;s small step.</h1><p className="mt-6 max-w-lg text-lg leading-8 text-white/55">Bangun rutinitas pencarian kerja yang konsisten, kelola setiap peluang, dan lihat progres kariermu dalam satu tempat.</p><div className="mt-10 grid grid-cols-3 gap-5 border-t border-white/10 pt-8">{["Daily streak","Smart pipeline","Clear insights"].map(item=><div key={item} className="flex items-center gap-2 text-sm text-white/70"><CheckCircle2 size={17} className="text-teal"/>{item}</div>)}</div></div><p className="relative text-xs text-white/25">© 2026 JobTrackr. Built for consistent career growth.</p></section>
    <section className="flex min-h-screen items-center justify-center px-6 py-10"><div className="w-full max-w-md"><a href="/" className="mb-9 flex items-center gap-2 lg:hidden"><span className="grid h-9 w-9 place-items-center rounded-xl bg-teal font-bold text-white">J</span><span className="text-xl font-bold text-navy">JobTrackr</span></a><div className="mb-6 grid h-12 w-12 place-items-center rounded-2xl bg-teal-50 text-teal-600"><BriefcaseBusiness size={23}/></div><h2 className="text-3xl font-bold tracking-tight text-navy">{mode==="login"?"Welcome back":"Start your journey"}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{mode==="login"?"Masuk menggunakan email dan password akunmu.":"Buat akun, lalu aktifkan melalui link verifikasi email."}</p>
      <div className="mt-7 grid grid-cols-2 rounded-xl bg-slate-100 p-1">{(["login","register"] as const).map(tab=><button key={tab} onClick={()=>{setMode(tab);setMessage(null)}} className={`rounded-lg py-2.5 text-sm font-semibold transition ${mode===tab?"bg-white text-navy shadow-sm":"text-slate-400"}`}>{tab==="login"?"Login":"Register"}</button>)}</div>
      <form className="mt-6 space-y-4" onSubmit={submit}><label className="block text-sm font-semibold text-navy">Email address<div className="mt-2 flex items-center gap-3 rounded-xl border border-slate-200 px-4 py-3.5 focus-within:border-teal focus-within:ring-4 focus-within:ring-teal/10"><Mail size={18} className="text-slate-400"/><input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" className="w-full bg-transparent text-sm font-normal outline-none placeholder:text-slate-300"/></div></label><label className="block text-sm font-semibold text-navy">Password<div className="mt-2 flex items-center gap-3 rounded-xl border border-slate-200 px-4 py-3.5 focus-within:border-teal focus-within:ring-4 focus-within:ring-teal/10"><LockKeyhole size={18} className="text-slate-400"/><input type={showPassword?"text":"password"} required minLength={8} autoComplete={mode==="login"?"current-password":"new-password"} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Minimum 8 characters" className="w-full bg-transparent text-sm font-normal outline-none placeholder:text-slate-300"/><button type="button" onClick={()=>setShowPassword(v=>!v)} className="text-slate-400" aria-label="Toggle password visibility">{showPassword?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label><button disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-xl bg-navy px-5 py-3.5 text-sm font-semibold text-white hover:bg-navy-700 disabled:opacity-60">{loading?<Loader2 size={18} className="animate-spin"/>:<>{mode==="login"?"Login":"Create account"}<ArrowRight size={17}/></>}</button></form>
      <div className="my-5 flex items-center gap-3"><div className="h-px flex-1 bg-slate-200"/><span className="text-[11px] uppercase tracking-wider text-slate-400">or continue with</span><div className="h-px flex-1 bg-slate-200"/></div><button onClick={loginGoogle} disabled={googleLoading} className="flex w-full items-center justify-center gap-3 rounded-xl border border-slate-200 bg-white px-5 py-3.5 text-sm font-semibold text-slate-700 hover:bg-slate-50 disabled:opacity-60">{googleLoading?<Loader2 size={18} className="animate-spin"/>:<><GoogleIcon/> Continue with Google</>}</button>
      {message&&<div className={`mt-4 rounded-xl border p-3 text-xs leading-5 ${message.type==="ok"?"border-teal-100 bg-teal-50 text-teal-700":"border-rose-100 bg-rose-50 text-rose-600"}`}>{message.text}</div>}<p className="mt-5 text-center text-xs leading-5 text-slate-400">{mode==="register"?"Dengan mendaftar, kamu menyetujui Terms dan Privacy Policy.":"Belum punya akun? Pilih Register di atas."}</p></div></section>
  </main>;
}
function GoogleIcon(){return <svg viewBox="0 0 24 24" className="h-[18px] w-[18px]" aria-hidden="true"><path fill="#4285F4" d="M21.6 12.2c0-.7-.1-1.4-.2-2H12v3.9h5.4a4.6 4.6 0 0 1-2 3v2.6h3.3c1.9-1.8 2.9-4.4 2.9-7.5Z"/><path fill="#34A853" d="M12 22c2.7 0 5-.9 6.7-2.3l-3.3-2.6c-.9.6-2 1-3.4 1-2.6 0-4.8-1.8-5.6-4.1H3v2.7A10 10 0 0 0 12 22Z"/><path fill="#FBBC05" d="M6.4 14a6 6 0 0 1 0-3.9V7.4H3a10 10 0 0 0 0 9.3L6.4 14Z"/><path fill="#EA4335" d="M12 5.9c1.5 0 2.8.5 3.8 1.5l2.9-2.8A9.7 9.7 0 0 0 3 7.4l3.4 2.7C7.2 7.7 9.4 6 12 6Z"/></svg>}
