"use client";
import { BriefcaseBusiness, Clock3, Flame, Plus, TrendingUp } from "lucide-react";
import { WorkspacePage } from "./workspace-page";
import { useStore } from "@/lib/store";

const activeStatuses=["Applied","HR Screening","Assessment","HR Interview","User Interview","Final Interview","Offering"];
export function Dashboard(){const{applications,logs,profile,user}=useStore();const applied=applications.filter(a=>a.current_status!=="Wishlist");const active=applications.filter(a=>activeStatuses.includes(a.current_status));const responded=applications.filter(a=>!["Wishlist","Applied","Ghosted"].includes(a.current_status));const response=applied.length?Math.round(responded.length/applied.length*100):0;const today=new Date().toISOString().slice(0,10);const todayDone=applications.some(a=>a.applied_date===today);const name=profile?.full_name||user?.user_metadata?.full_name||user?.email?.split("@")[0]||"there";
 return <WorkspacePage title="Dashboard Overview" eyebrow="Your career workspace" action={<a href="/applications?new=1" className="flex items-center gap-2 rounded-xl bg-navy px-5 py-3 text-sm font-semibold text-white"><Plus size={17}/> Add today&apos;s application</a>}>
  <section className="mb-7"><p className="text-sm font-semibold text-teal-600">Keep the momentum going</p><h2 className="mt-1 text-3xl font-bold text-navy">Good morning, {name}.</h2><p className="mt-1 text-sm text-slate-500">Small steps add up. Your next opportunity is one application away.</p></section>
  {!applications.length&&<div className="mb-6 rounded-2xl border border-dashed border-teal-300 bg-teal-50 p-8 text-center"><BriefcaseBusiness className="mx-auto text-teal-600"/><h3 className="mt-3 font-bold text-navy">Your pipeline is empty</h3><p className="mt-1 text-sm text-slate-500">Add your first application to begin tracking your progress.</p><a href="/applications?new=1" className="mt-4 inline-flex rounded-xl bg-teal px-5 py-3 text-sm font-semibold text-white">Add first application</a></div>}
  <section className="grid gap-5 md:grid-cols-2"><div className="rounded-2xl bg-navy p-6 text-white"><div className="flex items-center gap-4"><div className="grid h-12 w-12 place-items-center rounded-xl bg-orange-400/15 text-orange-300"><Flame/></div><div><p className="text-3xl font-bold">{todayDone?1:0} <span className="text-sm text-white/60">day streak</span></p><p className="text-xs text-white/45">{todayDone?"Today's goal completed.":"Add one application today."}</p></div></div></div><div className="rounded-2xl border border-teal-100 bg-teal-50 p-6"><p className="text-xs font-bold text-teal-600">DAILY GOAL</p><p className="mt-2 text-3xl font-bold text-navy">{todayDone?1:0} <span className="text-base text-slate-400">/ {profile?.daily_goal||1}</span></p></div></section>
  <section className="my-5 grid gap-5 sm:grid-cols-3"><Stat icon={BriefcaseBusiness} label="Total Applied" value={applied.length}/><Stat icon={Clock3} label="Active Pipeline" value={active.length}/><Stat icon={TrendingUp} label="Response Rate" value={`${response}%`}/></section>
  <section className="grid gap-5 xl:grid-cols-[1fr_340px]"><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-card"><div className="flex justify-between"><div><h3 className="font-bold text-navy">Application Pipeline</h3><p className="text-xs text-slate-400">Your active opportunities</p></div><a href="/applications" className="text-xs font-semibold text-teal-600">View all →</a></div><div className="mt-5 grid gap-3 md:grid-cols-4">{["Applied","HR Screening","Assessment","HR Interview"].map(s=><div key={s} className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-bold text-slate-600">{s} · {applications.filter(a=>a.current_status===s).length}</p>{applications.filter(a=>a.current_status===s).slice(0,3).map(a=><a href="/applications" key={a.id} className="mt-2 block rounded-lg border bg-white p-3"><p className="text-xs font-semibold text-navy">{a.position_title}</p><p className="text-[10px] text-slate-400">{a.companies?.name}</p></a>)}</div>)}</div></div><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-card"><h3 className="font-bold text-navy">Recent Activity</h3>{logs.slice(0,6).map(l=><div key={l.id} className="mt-4 border-t border-slate-100 pt-4"><p className="text-xs font-semibold text-navy">{l.notes||l.status_stage}</p><p className="text-[10px] text-slate-400">{new Date(l.created_at).toLocaleString()}</p></div>)}{!logs.length&&<p className="mt-5 text-xs text-slate-400">No activity yet.</p>}</div></section>
 </WorkspacePage>}
function Stat({icon:Icon,label,value}:{icon:typeof BriefcaseBusiness;label:string;value:string|number}){return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-card"><Icon className="text-teal-600" size={20}/><p className="mt-4 text-xs text-slate-400">{label}</p><p className="mt-1 text-2xl font-bold text-navy">{value}</p></div>}
