"use client";
import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import type { User } from "@supabase/supabase-js";
import { createClient } from "./supabase/client";

export type Company={id:string;name:string;industry:string|null;scale:string|null;location_type:string|null;summary:string|null;culture_notes:string|null;website_url:string|null};
export type Application={id:string;company_id:string;position_title:string;source:string|null;current_status:string;expected_salary:number|null;benefits_notes:string|null;cv_version_used:string|null;cover_letter_notes:string|null;applied_date:string|null;updated_at:string;companies?:Company};
export type Log={id:string;application_id:string;log_date:string;status_stage:string;notes:string|null;pic_name:string|null;pic_contact:string|null;created_at:string};
export type Profile={id:string;email:string;full_name:string|null;daily_goal:number};
type Store={loading:boolean;user:User|null;profile:Profile|null;companies:Company[];applications:Application[];logs:Log[];error:string|null;refresh:()=>Promise<void>;addCompany:(v:Omit<Company,"id">)=>Promise<string>;updateCompany:(id:string,v:Partial<Company>)=>Promise<void>;deleteCompany:(id:string)=>Promise<void>;addApplication:(v:Omit<Application,"id"|"updated_at"|"companies">)=>Promise<string>;updateApplication:(id:string,v:Partial<Application>)=>Promise<void>;deleteApplication:(id:string)=>Promise<void>;updateProfile:(v:Partial<Profile>)=>Promise<void>;logout:()=>Promise<void>};
const C=createContext<Store|null>(null);
export function StoreProvider({children}:{children:React.ReactNode}){const[user,setUser]=useState<User|null>(null);const[profile,setProfile]=useState<Profile|null>(null);const[companies,setCompanies]=useState<Company[]>([]);const[applications,setApplications]=useState<Application[]>([]);const[logs,setLogs]=useState<Log[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const sb=useMemo(()=>createClient(),[]);
 const refresh=useCallback(async()=>{if(!sb){setError("Supabase belum dikonfigurasi");setLoading(false);return}setLoading(true);const{data:{user:u}}=await sb.auth.getUser();setUser(u);if(!u){setProfile(null);setCompanies([]);setApplications([]);setLogs([]);setLoading(false);return}const[p,c,a,l]=await Promise.all([sb.from("profiles").select("*").single(),sb.from("companies").select("*").order("name"),sb.from("applications").select("*,companies(*)").order("updated_at",{ascending:false}),sb.from("application_logs").select("*").order("created_at",{ascending:false})]);setProfile(p.data);setCompanies(c.data||[]);setApplications((a.data||[]) as Application[]);setLogs(l.data||[]);setError(p.error?.message||c.error?.message||a.error?.message||l.error?.message||null);setLoading(false)},[sb]);
 useEffect(()=>{refresh();if(!sb)return;const{data}=sb.auth.onAuthStateChange(()=>refresh());return()=>data.subscription.unsubscribe()},[refresh,sb]);
 async function addCompany(v:Omit<Company,"id">){if(!sb)throw Error("Supabase unavailable");const{data,error}=await sb.from("companies").insert(v).select("id").single();if(error)throw error;await refresh();return data.id}
 async function updateCompany(id:string,v:Partial<Company>){if(!sb)return;const{error}=await sb.from("companies").update(v).eq("id",id);if(error)throw error;await refresh()}
 async function deleteCompany(id:string){if(!sb)return;const{error}=await sb.from("companies").delete().eq("id",id);if(error)throw error;await refresh()}
 async function addApplication(v:Omit<Application,"id"|"updated_at"|"companies">){if(!sb)throw Error("Supabase unavailable");const{data,error}=await sb.from("applications").insert(v).select("id").single();if(error)throw error;await sb.from("application_logs").insert({application_id:data.id,status_stage:v.current_status,notes:"Application created",log_date:new Date().toISOString().slice(0,10)});await refresh();return data.id}
 async function updateApplication(id:string,v:Partial<Application>){if(!sb)return;const old=applications.find(x=>x.id===id);const changes={...v};if(changes.current_status&&changes.current_status!=="Wishlist"&&!old?.applied_date)changes.applied_date=new Date().toISOString().slice(0,10);const{error}=await sb.from("applications").update(changes).eq("id",id);if(error)throw error;if(v.current_status&&v.current_status!==old?.current_status)await sb.from("application_logs").insert({application_id:id,status_stage:v.current_status,notes:`Status changed from ${old?.current_status} to ${v.current_status}`,log_date:new Date().toISOString().slice(0,10)});await refresh()}
 async function deleteApplication(id:string){if(!sb)return;const{error}=await sb.from("applications").delete().eq("id",id);if(error)throw error;await refresh()}
 async function updateProfile(v:Partial<Profile>){if(!sb||!user)return;const{error}=await sb.from("profiles").update(v).eq("id",user.id);if(error)throw error;await refresh()}
 async function logout(){if(sb)await sb.auth.signOut();window.location.href="/"}
 return <C.Provider value={{loading,user,profile,companies,applications,logs,error,refresh,addCompany,updateCompany,deleteCompany,addApplication,updateApplication,deleteApplication,updateProfile,logout}}>{children}</C.Provider>}
export function useStore(){const v=useContext(C);if(!v)throw Error("StoreProvider missing");return v}
